"""empty message

Revision ID: 80dc3b2b82d5
Revises: fa467b7eb002
Create Date: 2020-11-21 21:53:41.026589

"""

import pathlib
import sys; sys.path.append(str(pathlib.Path().absolute()))
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80dc3b2b82d5'
down_revision = 'fa467b7eb002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_places',
        sa.Column('lesson_id', sa.Integer(), nullable=True),
        sa.Column('place_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
        sa.ForeignKeyConstraint(['place_id'], ['places.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_places')
    # ### end Alembic commands ###
