"""empty message

Revision ID: 9359a07c044a
Revises: b77dbceec276
Create Date: 2020-11-22 05:15:34.437174

"""

import pathlib
import sys; sys.path.append(str(pathlib.Path().absolute()))
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9359a07c044a'
down_revision = 'b77dbceec276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('second_weeknum', sa.Boolean(), nullable=True))
    op.drop_column('lessons', 'weeknum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('weeknum', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('lessons', 'second_weeknum')
    # ### end Alembic commands ###
