"""empty message

Revision ID: b77dbceec276
Revises: 80dc3b2b82d5
Create Date: 2020-11-21 21:56:37.436011

"""

import pathlib
import sys; sys.path.append(str(pathlib.Path().absolute()))
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77dbceec276'
down_revision = '80dc3b2b82d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lessons_place_ids_fkey', 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'place_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('place_ids', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('lessons_place_ids_fkey', 'lessons', 'places', ['place_ids'], ['id'])
    # ### end Alembic commands ###
