"""empty message

Revision ID: c58f442e12ce
Revises: 
Create Date: 2020-11-18 23:16:04.837675

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c58f442e12ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditory')
    op.add_column('buildings', sa.Column('subgroup', sa.Enum('1', '2', name='subgroup'), nullable=True))
    op.add_column('groups', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('groups', 'number')
    op.add_column('lessons', sa.Column('group_ids', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('place_ids', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('teacher_ids', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('weeknum', sa.Boolean(), nullable=True))
    op.alter_column('lessons', 'subgroup',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='0 is a first subgroup, 1 - second',
               existing_nullable=True)
    op.create_foreign_key(None, 'lessons', 'groups', ['group_ids'], ['id'])
    op.create_foreign_key(None, 'lessons', 'places', ['place_ids'], ['id'])
    op.create_foreign_key(None, 'lessons', 'teachers', ['teacher_ids'], ['id'])
    op.drop_column('lessons', 'building')
    op.add_column('places', sa.Column('building_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'places', 'buildings', ['building_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'places', type_='foreignkey')
    op.drop_column('places', 'building_id')
    op.add_column('lessons', sa.Column('building', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.alter_column('lessons', 'subgroup',
               existing_type=sa.BOOLEAN(),
               comment='0 is a first subgroup, 1 - second',
               existing_nullable=True)
    op.drop_column('lessons', 'weeknum')
    op.drop_column('lessons', 'teacher_ids')
    op.drop_column('lessons', 'place_ids')
    op.drop_column('lessons', 'group_ids')
    op.add_column('groups', sa.Column('number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('groups', 'name')
    op.drop_column('buildings', 'subgroup')
    op.create_table('auditory',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='auditory_pkey')
    )
    # ### end Alembic commands ###
