"""Remove incorrectly created field Building.subgroup

Revision ID: d62f71fd0e9f
Revises: c58f442e12ce
Create Date: 2020-11-19 16:47:11.341426

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd62f71fd0e9f'
down_revision = 'c58f442e12ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'subgroup')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('subgroup', postgresql.ENUM('1', '2', name='subgroup'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
