"""Created many-to-many relationship lesson_groups

Revision ID: f7567c08a197
Revises: d8be8e5e3001
Create Date: 2020-11-21 03:02:27.111456

"""

import pathlib
import sys; sys.path.append(str(pathlib.Path().absolute()))
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7567c08a197'
down_revision = 'd8be8e5e3001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_groups',
        sa.Column('lesson_id', sa.Integer(), nullable=True),
        sa.Column('group_name', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['group_name'], ['groups.name'], ),
        sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], )
    )
    # op.drop_constraint('buildings_name_key', 'buildings', type_='unique')
    # op.drop_constraint('groups_name_key', 'groups', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('groups_name_key', 'groups', ['name'])
    # op.create_unique_constraint('buildings_name_key', 'buildings', ['name'])
    op.drop_table('lesson_groups')
    # ### end Alembic commands ###
