"""empty message

Revision ID: fa467b7eb002
Revises: f7567c08a197
Create Date: 2020-11-21 03:15:09.980732

"""

import pathlib
import sys; sys.path.append(str(pathlib.Path().absolute()))
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa467b7eb002'
down_revision = 'f7567c08a197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('buildings_name_key', 'buildings', type_='unique')
    # op.drop_constraint('groups_name_key', 'groups', type_='unique')
    op.drop_constraint('lessons_group_names_fkey', 'lessons', type_='foreignkey')
    op.drop_constraint('lessons_teacher_ids_fkey', 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'group_names')
    op.drop_column('lessons', 'teacher_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('teacher_ids', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lessons', sa.Column('group_names', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('lessons_teacher_ids_fkey', 'lessons', 'teachers', ['teacher_ids'], ['id'])
    op.create_foreign_key('lessons_group_names_fkey', 'lessons', 'groups', ['group_names'], ['name'])
    # op.create_unique_constraint('groups_name_key', 'groups', ['name'])
    # op.create_unique_constraint('buildings_name_key', 'buildings', ['name'])
    # ### end Alembic commands ###
